Does not seem to be picking up Gemfile fix

diff --git a/.github/workflows/adhoc.yml b/.github/workflows/adhoc.yml
--- a/.github/workflows/adhoc.yml
+++ b/.github/workflows/adhoc.yml
@@ -25,8 +25,8 @@ jobs:
         #    timeout: 5
         #  - ruby: '3.0'
         #    timeout: 5
-         - ruby: 3.1
-           timeout: 5
+        #  - ruby: 3.1
+        #    timeout: 5
         #  - ruby: truffleruby
         #    timeout: 50
         #  - ruby: truffleruby-head
@@ -39,8 +39,8 @@ jobs:
         #    timeout: 5
          - ruby: jruby-9.3
            timeout: 10
-         - ruby: jruby-9.2
-           timeout: 10
+        #  - ruby: jruby-9.2
+        #    timeout: 10
     steps:
     - name: Psych 5.0.0 needs libyaml-dev
       run: |
@@ -55,25 +55,32 @@ jobs:
         # rubygems: 3.2.3
         # bundler-cache: true
     - name: Install dependencies
-      run: bundle install
+      run: |
+        cat Gemfile
+        bundle install
+        gem list psych
+        gem uninstall psych -v 5.0.0
+        gem install psych -v 4.0.6
+        gem list psych
+      continue-on-error: true
     - name: Run tests1
       run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
-    - name: Run tests2
-      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
-    - name: Run tests3
-      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
-    - name: Run tests4
-      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
-    - name: Run tests5
-      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
-    - name: Run tests6
-      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
-      continue-on-error: true
+    #   continue-on-error: true
+    # - name: Run tests2
+    #   run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
+    #   continue-on-error: true
+    # - name: Run tests3
+    #   run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
+    #   continue-on-error: true
+    # - name: Run tests4
+    #   run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
+    #   continue-on-error: true
+    # - name: Run tests5
+    #   run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
+    #   continue-on-error: true
+    # - name: Run tests6
+    #   run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
+    #   continue-on-error: true
     - name: Run Summary
       run: |
         echo "${{ env.action_state }}"
