Can we cache the status?

diff --git a/.github/workflows/adhoc.yml b/.github/workflows/adhoc.yml
--- a/.github/workflows/adhoc.yml
+++ b/.github/workflows/adhoc.yml
@@ -55,17 +55,21 @@ jobs:
     - name: Install dependencies
       run: bundle install
     - name: Run tests1
-      run: bundle exec rake spec
+      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
       continue-on-error: true
     - name: Run tests2
-      run: bundle exec rake spec
+      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
       continue-on-error: true
     - name: Run tests3
-      run: bundle exec rake spec
+      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
       continue-on-error: true
     - name: Run tests4
-      run: bundle exec rake spec
+      run: bundle exec rake spec || echo "action_state=failed" >> $GITHUB_ENV
       continue-on-error: true
+    - name: Run Summary
+      run: |
+        - echo "${{ env.action_state }}"
+        - test "${{ env.action_state }}" == 'failed' && exit 1
       # continue-on-error: ${{ matrix.ruby == 'truffleruby-head' }}
   # actionmailer:
   #   runs-on: ubuntu-latest
